# Generated by Django 2.2.7 on 2021-04-18 15:12

import django.core.files.storage
from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='First Name', max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Last Name', max_length=50, verbose_name='Last Name')),
                ('profile_photo', models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='', location=''), upload_to='attachments/')),
                ('gender', models.CharField(choices=[(None, 'Choose your gender'), ('male', 'male'), ('female', 'female'), ('Prefer Not To Say', 'Prefer Not To Say')], default=None, max_length=30)),
                ('medical_condition', models.CharField(max_length=300, verbose_name='Medical Conditions')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('is_previous_student', models.NullBooleanField(default=False)),
                ('islamic_studies_grade_prev_year', models.IntegerField()),
                ('iqra_grade_prev_year', models.IntegerField()),
                ('enrolment_for_year', models.IntegerField()),
                ('referee_name', models.CharField(help_text='Referee Name', max_length=50, verbose_name='Referee Name')),
                ('referee_email_address', models.EmailField(max_length=250)),
                ('referee_phone_number', phone_field.models.PhoneField(help_text='Referee Mobile Number', max_length=31)),
                ('father_name', models.CharField(help_text='Father Name', max_length=100, verbose_name='Father Name')),
                ('mother_name', models.CharField(help_text='Mother Name', max_length=100, verbose_name='Mother Name')),
                ('father_email', models.EmailField(max_length=250)),
                ('mother_email', models.EmailField(max_length=250)),
                ('father_contact_number', phone_field.models.PhoneField(help_text='Father Mobile Number', max_length=31)),
                ('mother_contact_number', phone_field.models.PhoneField(help_text='Mother Mobile Number', max_length=31)),
                ('ambulance_cover', models.NullBooleanField(default=False)),
                ('ambulance_membership_number', models.CharField(max_length=100)),
                ('home_address', models.CharField(help_text='Home Address', max_length=250, verbose_name='Home Address')),
                ('preferred_contact_for_correspondence', models.CharField(max_length=150)),
                ('email_for_correspondence', models.EmailField(max_length=250)),
                ('fees_paid', models.NullBooleanField(default=False)),
                ('current_record', models.NullBooleanField(default=False)),
                ('status', models.CharField(max_length=100)),
                ('active_record', models.NullBooleanField(default=False)),
            ],
            options={
                'db_table': 'student_details',
            },
        ),
    ]
