# Generated by Django 2.2.7 on 2021-04-18 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('template_id', models.IntegerField(primary_key=True, serialize=False)),
                ('template_subject', models.CharField(help_text='Template Subject', max_length=100, verbose_name='Template Subject')),
                ('template_body', models.CharField(help_text='Template Body', max_length=250, verbose_name='Template Body')),
            ],
            options={
                'db_table': 'template',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_class', models.DateField(verbose_name='Date of class')),
                ('is_present', models.NullBooleanField(default=False)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='student_registration.StudentDetails')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
    ]
