# Generated by Django 2.2.7 on 2021-04-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0002_attendance_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='student_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
