# Generated by Django 2.2.7 on 2021-05-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0003_auto_20210418_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='active_record',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='ambulance_cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='current_record',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='fees_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='is_previous_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='status',
            field=models.CharField(choices=[(None, 'Choose status'), ('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], max_length=100),
        ),
    ]
