# Generated by Django 2.2.7 on 2021-05-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0004_auto_20210502_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='template_name',
            field=models.CharField(default=None, help_text='Template Name', max_length=100, verbose_name='Template Name'),
            preserve_default=False,
        ),
    ]
