# Generated by Django 2.2.7 on 2021-05-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0005_template_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='iqra_grade_prev_year',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='islamic_studies_grade_prev_year',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
