# Generated by Django 3.1.7 on 2021-05-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0008_auto_20210515_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='iqra_grade_prev_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='islamic_studies_grade_prev_year',
            field=models.IntegerField(null=True),
        ),
    ]
