# Generated by Django 3.1.7 on 2021-05-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0009_auto_20210515_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='ambulance_membership_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
