# Generated by Django 3.1.7 on 2021-05-15 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0010_auto_20210515_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
