# Generated by Django 3.1.7 on 2021-05-22 17:41

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0011_studentdetails_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='active_record',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='referee_email_address',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='referee_name',
            field=models.CharField(blank=True, help_text='Referee Name', max_length=50, null=True, verbose_name='Referee Name'),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='referee_phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Referee Mobile Number', max_length=31),
        ),
    ]
