# Generated by Django 3.1.7 on 2021-05-23 05:42

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0013_merge_20210523_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='referee_phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Referee Mobile Number', max_length=31, null=True),
        ),
    ]
