# Generated by Django 3.1.7 on 2021-05-23 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0015_auto_20210523_0652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='student_id',
            new_name='student',
        ),
    ]
