# Generated by Django 3.1.7 on 2021-05-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0017_auto_20210523_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='grade_in_school',
            field=models.IntegerField(null=True),
        ),
    ]
