# Generated by Django 3.1.7 on 2021-05-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0019_auto_20210529_1422'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='studentdetails',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'dob'), name='student_unique'),
        ),
    ]
