# Generated by Django 3.1.7 on 2021-05-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0021_auto_20210529_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template_body',
            field=models.TextField(help_text='Template Body', verbose_name='Template Body'),
        ),
    ]
