# Generated by Django 3.1.7 on 2021-05-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0022_auto_20210529_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='email_for_correspondence',
            field=models.EmailField(max_length=250, verbose_name='Email'),
        ),
    ]
