# Generated by Django 3.1.7 on 2021-05-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0023_auto_20210530_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student_name',
            field=models.CharField(help_text='Student Name', max_length=100, verbose_name='Student Name'),
        ),
    ]
