# Generated by Django 3.1.7 on 2021-05-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0024_auto_20210530_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='iqra_grade_prev_year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='islamic_studies_grade_prev_year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
