# Generated by Django 3.1.7 on 2021-05-30 06:53

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0025_auto_20210530_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='current_record',
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='father_contact_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Father Mobile Number', max_length=31),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='father_email',
            field=models.EmailField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='father_name',
            field=models.CharField(blank=True, help_text='Father Name', max_length=100, verbose_name='Father Name'),
        ),
    ]
