# Generated by Django 3.1.7 on 2021-05-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0026_auto_20210530_0653'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'date'), name='name of constraint'),
        ),
    ]
