# Generated by Django 2.2.7 on 2021-07-18 05:51

from django.db import migrations, models
import student_registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0028_auto_20210718_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='student_id',
            field=models.CharField(default=student_registration.models.generate_student_id, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
