# Generated by Django 2.2.7 on 2021-08-04 04:05

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0030_studentdetails_current_islamic_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='date_of_payment',
            field=models.DateField(null=True, verbose_name='Date of payment'),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='paid_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='mother_contact_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Mother Mobile Number', max_length=31),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='mother_email',
            field=models.EmailField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='mother_name',
            field=models.CharField(blank=True, help_text='Mother Name', max_length=100, verbose_name='Mother Name'),
        ),
    ]
